'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ProjectManagementEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ProjectManagementEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Durations() As DbSet(Of Duration)
    Public Overridable Property Projects() As DbSet(Of Project)
    Public Overridable Property ProjectTypes() As DbSet(Of ProjectType)
    Public Overridable Property Resources() As DbSet(Of Resource)
    Public Overridable Property Statuses() As DbSet(Of Status)
    Public Overridable Property Tasks() As DbSet(Of Task)

End Class
