'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Project
    Public Property ProjectId As Integer
    Public Property ClientName As String
    Public Property ProjectName As String
    Public Property Technology As String
    Public Property ProjectType As String
    Public Property UserId As String
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property Cost As Decimal

    Public Overridable Property Tasks As ICollection(Of Task) = New HashSet(Of Task)

End Class
